server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.114:8071/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.account

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    password: 123456
    username: tung
    url: jdbc:mysql://192.168.6.114:3306/account_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  zipkin:
    base-url: http://192.168.6.114:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 10.10.2.202:29092

system:
  supperAdmin:
    fullname: admin
    username: admin
    email: admin@gmail.com
    password: Admin@123
    organization: Comit

app:
  jwtExpirationInMs: 1209600000
  jwtSecret: comit_admin
  internalToken: YWRtaW4vQWRtaW5AMTIz
