server:
  port: 8071

eureka:
  instance:
    hostname: 192.168.6.113
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  zipkin:
    base-url: http://192.168.6.113:9411
  sleuth:
    sampler:
      probability: 1.0