server:
  port: 8071

eureka:
  instance:
    hostname: 10.10.2.113
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  zipkin:
    base-url: http://10.10.2.113:9411
  sleuth:
    sampler:
      probability: 1.0