server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.114:8071/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.employee

spring:
  datasource:
    username: tung
    url: jdbc:mysql://192.168.6.114:3306/employee_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://192.168.6.114:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 10.10.2.202:29092

core:
  api:
    add-employee-image: http://192.168.6.111:5678/embedding/
    update-employee-image: http://192.168.6.111:5678/embedding
    delete-employee-image: http://192.168.6.111:5678/embedding

app:
  internalToken: YWRtaW4vQWRtaW5AMTIz