server:
  port: 8084

eureka:
  instance:
    preferIpAddress: true
    hostname: k8s-discovery-service-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8s-discovery-service-0.discovery-service.default.svc.cluster.local:8071/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.employee

spring:
  datasource:
    username: ${DATABASE_USERNAME}
    url: jdbc:mysql://${DATABASE_SERVER_ADDRESS}/employee_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_ADDRESS}

core:
  api:
    add-employee-image: ${ACTION_EMPLOYEE_IMAGE_URL}/
    update-employee-image: ${ACTION_EMPLOYEE_IMAGE_URL}
    delete-employee-image: ${ACTION_EMPLOYEE_IMAGE_URL}