server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.2.113:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.feature

spring:
  datasource:
    username: tung
    url: jdbc:mysql://10.10.2.113:3306/feature_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://10.10.2.113:9411
  sleuth:
    sampler:
      probability: 1.0