server:
  port: 8087

eureka:
  instance:
    preferIpAddress: true
    hostname: k8n-discovery-service-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8n-discovery-service-0.discovery-service.default.svc.cluster.local:8071/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.history

spring:
  datasource:
    username: tung
    url: jdbc:mysql://${DATABASE_SERVER_ADDRESS}/history_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0