server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
    hostname: k8s-discovery-service-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8s-discovery-service-0.discovery-service.default.svc.cluster.local:8071/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.mail

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    main:
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
    area:
      primary:
        username: ${MAIL_AREA_PRIMARY_USERNAME}
        password: ${MAIL_AREA_PRIMARY_PASSWORD}
      secondary:
        username: ${MAIL_AREA_SECONDARY_USERNAME}
        password: ${MAIL_AREA_SECONDARY_PASSWORD}
    tk:
      primary:
        username: ${MAIL_TK_PRIMARY_USERNAME}
        password: ${MAIL_TK_PRIMARY_PASSWORD}
      secondary:
        username: ${MAIL_TK_SECONDARY_USERNAME}
        password: ${MAIL_TK_SECONDARY_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: false
  datasource:
    username: tung
    url: jdbc:mysql://${DATABASE_SERVER_ADDRESS}/mail_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_ADDRESS}

#QRCode Telegram
qrcode:
  image:
    url: https://drive.google.com/uc?export=view&id=1VMcOxFtm0aePzWOGz-cwOugR0tu8heG4
  url: t.me/ComitBot

#Frontend Server
frontend:
  server: ${CHANGE_PASSWORD_URL}
app:
  internalToken: YWRtaW4vQWRtaW5AMTIz