server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
    hostname: k8n-discovery-service-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8n-discovery-service-0.discovery-service.default.svc.cluster.local:8071/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.mail

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sinhvienitpro95@gmail.com
    password: zajgpbjjcxxhvtjn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: false
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_ADDRESS}

#QRCode Telegram
qrcode:
  image:
    url: https://drive.google.com/uc?export=view&id=1VMcOxFtm0aePzWOGz-cwOugR0tu8heG4
  url: t.me/ComitBot