server:
  port: 8091

eureka:
  instance:
    preferIpAddress: true
    hostname: k8s-discovery-service-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8s-discovery-service-0.discovery-service.default.svc.cluster.local:8071/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.metadata

spring:
  datasource:
    username: ${DATABASE_USERNAME}
    url: jdbc:mysql://${DATABASE_SERVER_ADDRESS}/metadata_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0
#Storage
  storage:
    host: http://${STORAGE_HOST}
    folder: ${STORAGE_FOLDER}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB