server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.114:8071/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.metadata

spring:
  datasource:
    username: tung
    url: jdbc:mysql://192.168.6.114:3306/metadata_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://192.168.6.114:9411
  sleuth:
    sampler:
      probability: 1.0
#Storage
  storage:
    host: http://192.168.6.114
    folder: /Users/nguyentung/Desktop/Project/GSTTAN/admin_server/file_uploads
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

app:
  internalToken: YWRtaW4vQWRtaW5AMTIz