server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.6.113:8071/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.comit.services.organization

spring:
  datasource:
    username: tung
    url: jdbc:mysql://192.168.6.113:3306/organization_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://192.168.6.113:9411
  sleuth:
    sampler:
      probability: 1.0
system:
  supperAdmin:
    organization: Comit
app:
  internalToken: YWRtaW4vQWRtaW5AMTIz