server:
  port: 8071

eureka:
  instance:
    hostname: "${HOSTNAME}.discovery-service"
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_ADDRESS}

spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS}
  sleuth:
    sampler:
      probability: 1.0